version: "3.3"

services:
    prometheus:
        # build: ./prometheus
        image: abaco/prom$TAG
#        environment:
#            no_proxy: "reg"
        configs:
          - source: prometheus_config
            target: /etc/prometheus/prometheus.yml
          - source: prometheus_rules
            target: /etc/prometheus/alert.rules.yml
        command:
          - '--config.file=/etc/prometheus/prometheus.yml'
        #   - '-storage.local.path=/prometheus'
        ports:
            - 9090:9090
        deploy:
            placement:
                constraints:
                    - 'node.role == manager'
                    - 'node.platform.os == linux'
            resources:
                limits:
                    memory: 500M
                reservations:
                    memory: 200M
        networks:
            - prom

    grafana:
        image: grafana/grafana
        user: "104"
        depends_on:
            - prometheus
        ports:
            - 3000:3000
        volumes:
            - grafana_data:/var/lib/grafana
            - ./prometheus/grafana/provisioning/:/etc/grafana/provisioning/
        env_file:
            - ./prometheus/grafana/config.monitoring
        networks:
#            - back-tier
#            - front-tier
            - prom
        restart: always

    metrics:
        image: abaco/core$TAG
        networks:
            - prom
        volumes:
            - ./local-dev.conf:/etc/service.conf
            - ./abaco.log:/var/log/service.log
        ports:
            - "5004:5000"
        environment:
            server: dev
            api: metrics
            mongo_password:
            redis_password:
            TAS_ROLE_ACCT:
            TAS_ROLE_PASS:


volumes:
    grafana_data: {}

networks:
#    front-tier:
#    back-tier:
    prom:
        driver: bridge

#    alertmanager:
#        image: abaco/alert$TAG
##        environment:
##            no_proxy: "gateway"
#        command:
#            - '-config.file=/alertmanager.yml'
#        networks:
#            - testing
#        # Uncomment the following port mapping if you wish to expose the Prometheus
#        # Alertmanager UI.
#        ports:
#             - 9093:9093
#        deploy:
#            resources:
#                limits:
#                    memory: 50M
#                reservations:
#                    memory: 20M
#            placement:
#                constraints:
#                    - 'node.role == manager'
#                    - 'node.platform.os == linux'
#        configs:
#            - source: alertmanager_config
#              target: /alertmanager.yml
#
#
#configs:
#     prometheus_config:
#         file: ./prometheus/prometheus.yml
#     prometheus_rules:
#         file: ./prometheus/alert.rules.yml
#     alertmanager_config:
#         file: ./prometheus/alertmanager.yml
#
#networks:
#    testing:
#        driver: overlay
#        attachable: true
