---

- include_vars: "{{ abaco_env }}/settings.yml"
- include_vars: "{{ abaco_env }}/passwords.yml"

- name: Compile docker_compose template
  template: src=docker-compose-web.yml.j2 dest={{ base_dir }}/docker-compose-web.yml
  sudo: yes
  sudo_user: "{{ linux_user }}"

# ignore errors here since this call will fail if there are no containers running
- name: remove existing compute containers
  shell: docker-compose -f docker-compose-web.yml down
  sudo: yes
  sudo_user: "{{ linux_user }}"
  ignore_errors: yes

- name: start the containers with docker compose
  shell: docker-compose -f docker-compose-web.yml up -d chdir={{ base_dir }}
  sudo: yes
  sudo_user: "{{ linux_user }}"
  environment:
      COMPOSE_HTTP_TIMEOUT: 240